services:

  postgres:
    image: postgres:15
    container_name: gnuvet-db
    restart: always

    environment:
      POSTGRES_USER: gnuvet
      POSTGRES_PASSWORD: gnuvet
      POSTGRES_DB: gnuvet

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gnuvet"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: